/**
 * Generated `api` utility bootstrap.
 *
 * This file is normally regenerated by `npx convex dev` after a deployment is
 * configured. It is committed here so the fresh app typechecks before the first
 * Convex login/setup.
 */

import type { AnyApi } from "convex/server";
import { anyApi } from "convex/server";

export const api: AnyApi = anyApi;
export const internal: AnyApi = anyApi;
